### ISSUE TITLE
Value Map - Should Otherwise be required?

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#105]
When setting up a value map, should we require otherwise?  If a value is in the source and it does not have a value in the value map, is the source value used as is if otherwise is not specified?

If a value is not in the value map and otherwise is not specific, should we add a warning with teh value to let the user know they missed something?

@ChrisBuscaglia @SteveGrise

**Comment by SteveGrise** [comment]
Otherwise is meant for the special case where there may be a range of
source values for the same target. I think normally it is best to map all
values unless there is a case where the exceptions should all map to the
same value. In some cases this is valid so I do not see a need to indicate
that as an error/warning, on larger datasets it becomes quite noisy since
it is hard to know ahead of time how many times this could happen. For me
Preview helps with these situations to make sure the data is working
correctly.

**Comment by MikeMillerGIS** [comment]
- [ ] Test a value mapping where a value is not mapped and otherwise is not used, ensure an error is not presented

**Comment by previnWong** [comment]
@MikeMillerGIS have it valued to just 2 values (1,2,5,6,7 are missing).  Left Otherwise blank.
![image](https://cloud.githubusercontent.com/assets/11183838/24163104/d2db0642-0e26-11e7-8f5e-68277d17b632.png)

Throws an error.
![image](https://cloud.githubusercontent.com/assets/11183838/24163125/dcef51e2-0e26-11e7-834e-29f63c1ea5d1.png)

Completes successfully only when all values are mapped or if Otherwise is defined.  Maybe will be addressed with enhancement to pull value list.  Not sure how to show a friendlier message since it will probably need the code to pull a value list to do so anyway.

**Comment by MikeMillerGIS** [comment]
@SteveGrise what is the expectation here.  I feel any red error/exception is a bug.

**Comment by SteveGrise** [comment]
​I think there is a bug there - if there is no Otherwise I would expect the
function to behave like Copy.​

**Comment by SteveGrise** [comment]
But in the code it definitely is raising an error if there in no value map match and there is no Otherwise. I think we could assume that no Otherwise value means to copy the existing value or set to None - I'm not sure which would be the correct behavior if we relaxed the rules.

**Comment by MikeMillerGIS** [comment]
yes, lets go with that.  If I do not map it, and I do not set an otherwise, push it in as is.  I think that is the correct approach.

**Comment by previnWong** [comment]
@SteveGrise just trying to clarify the expected result.  So if Value Map is not fully defined for each value, and if Otherwise is not used, it will just perform copy of the missing values?

If so, I am not see that. I get an error and it fails to append.
![image](https://cloud.githubusercontent.com/assets/11183838/24619106/e07ff4f2-184d-11e7-94b4-c9573af0dae5.png)

**Comment by SteveGrise** [comment]
The way it has always worked is that if it finds values that are not
mapped, and there is no otherwise value, then it is an error. The idea is
the user should map all of the values and we don't want to introduce data
copying quietly since that could not be what they wanted to happen.

**Comment by previnWong** [comment]
closing as working as expected by the determined workflow.
