### ISSUE TITLE
UI not loading saved domain maps correctly

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#123]
Values are saved correctly in file but Source Values are not reloaded correctly in the form.

**Comment by SteveGrise** [comment]
While fixing this also added automatic mapping of domains where source coded value + description = target coded value + description. This is the logical behavior users will want when 2 domains are similar/identical.

**Comment by previnWong** [comment]
@SteveGrise is this fix in the Enhancement-WA1 branch release addin?  I am still seeing a shift in domains.
I left the first row blank since there is no matching source domain
![image](https://cloud.githubusercontent.com/assets/11183838/23476583/177b9314-fe70-11e6-9062-cf3a035dd274.png)

After applying and you switch field and come back, the values are shifted.
![image](https://cloud.githubusercontent.com/assets/11183838/23476643/4d436f3a-fe70-11e6-9e6b-2eac8620e091.png)

**Comment by SteveGrise** [comment]
Looks like a different issue to me. I spent time working on the save/reload
issue, it should be matching then correctly but this looks like a bug. I
did not have that issue in testing.

**Comment by SteveGrise** [comment]
which version are you using now? i can't tell from your message.

**Comment by previnWong** [comment]
I'm using this one.
https://github.com/Esri/data-assistant/tree/Enhancements-WA1/ShareGISData/bin/Release

**Comment by previnWong** [comment]
Verified resolved.

**Comment by MikeMillerGIS** [comment]
verified also
