### ISSUE TITLE
Arcpy da cursor field set to None is set to DefaultValue if there is a DefaultValue on the source field

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#130]
In testing setting values to None with Pro 1.4 this appears to be an issue on SQL server (have not tested others yet). In the example below the values are all set to None but in the database they are not updated.

![image](https://cloud.githubusercontent.com/assets/4749060/23761990/b4cbce74-04c2-11e7-989b-2c1474d12b79.png)

**Comment by SteveGrise** [comment]
After looking into this further this is the expected behavior for a dataset with a DefaultValue. It may be desirable to clear the intermediate dataset DefaultValues so that values that the user did not intend are set in the output data.

I'm attaching a test case. Here there are 3 source values set to 0 (Unknown) for diameter domain. In the updateCursor the value is set to None (4th item):
![image](https://cloud.githubusercontent.com/assets/4749060/23905198/a4254474-08a0-11e7-82b7-d68c7269d7cf.png)

but after calling updateRow from the fieldCalculator the value is set to 1:
![image](https://cloud.githubusercontent.com/assets/4749060/23905241/c1c549de-08a0-11e7-8613-292ce141f5ff.png)

[DomainTest.zip](https://github.com/Esri/data-assistant/files/841603/DomainTest.zip)

There is no domain on the intermediate table, but exporting the table appears to copy over the Default value of 1, and setting the value to None in the cursor sets the DefaultValue rather than null.

**Comment by MikeMillerGIS** [comment]
Can you use clear the Default values when generating the intermediate datasets?

**Comment by SteveGrise** [comment]
Yes, that looks like the best solution. This will only happen when there
are source and target field names with the same name, so I should be able
to find an efficient way to just clear those fields.

**Comment by previnWong** [comment]
@SteveGrise @MikeMillerGIS In the target, I added a default value in the diameter field (0). 
![image](https://cloud.githubusercontent.com/assets/11183838/24159284/f7f03c28-0e1b-11e7-8825-2400ba699e07.png)

 When I map the source  values Unknown, None, and 1 inch all to None in the target, 
![image](https://cloud.githubusercontent.com/assets/11183838/24159393/360421f0-0e1c-11e7-9586-9c108d695618.png)

the value saved to the target is NULL, not the default value.  Is that the expected behavior?
![image](https://cloud.githubusercontent.com/assets/11183838/24159222/d2f6c18a-0e1b-11e7-90c0-56295b688d63.png)

My thought would be, if the the target is NONE, then if the field does not have a default value, it would store NULL as it is doing.  But if the target field does have a default value, I would expect the default value to be used (in my test case 0).  If there is a default value in target, my assumption is that the DB designers wants a value in there, not NULL.

**Comment by MikeMillerGIS** [comment]
Verified
