### ISSUE TITLE
Preview Values prints 1.0 on numeric field if value is ""

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#153]
string value of empty string is 1

**Comment by SteveGrise** [comment]
Actually the value was being overwritten by later valuemap values even if there was a match in the data grid. Change to only set to Otherwise value if no match found.

**Comment by SteveGrise** [comment]
Also fix domain map preview to show the source value if no matching map value found.

**Comment by previnWong** [comment]
Preview shows "" now instead of 1.
![image](https://cloud.githubusercontent.com/assets/11183838/24431398/81054cec-13d0-11e7-91cb-9a2725284209.png)

But if I run the preview command, I get an error
![image](https://cloud.githubusercontent.com/assets/11183838/24431407/9132ec28-13d0-11e7-8cda-2ac32c8214c8.png)

**Comment by SteveGrise** [comment]
setvalue is blank, that's what I'd expect to see for a number field

**Comment by previnWong** [comment]
The errors are valid, since the field is required and it's an integer, just wondering if the messaging is is not user friendly.  Ot just do a simple data type check and return a friendly message right away.

**Comment by SteveGrise** [comment]
Yes, Preview Values could do type checking.

**Comment by previnWong** [comment]
initial issue is fixed.  UI could show better message for type cast error, but closing since UI is minor
