### ISSUE TITLE
A new method for domain mapping

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#60]
When loading data into the Utility Network, we will have to translate a lot of fields with domains to new codes.  To simplify this process, we would like a new method that would look at the source domain and target domain and let you map values.

**Comment by SteveGrise** [comment]
Keeping the domain values in the config files would increase the file sizes quite a bit because you'd have to store all of the domains. We could dynamically pull the domains from the source/target layers, it might be a bit slow to get the domains/values. Possibly loading the domain names in the Config file then grabbing specific values from the layer when the items are selected would be the best option.

Seems like Automatch could be trained for some of the common system/user mappings in this area, so things like diameter/kva/trace weight domains could be auto-set after the pattern is config'd 1 time. That would just copy the previous settings from the Automatch file and not involve a lot of processing/config time.

**Comment by MikeMillerGIS** [comment]
This will also have to account for domains that we auto convert to int and the user will have to match them up.  I do not think we need to store the domains in the config, just the tool present a dialog with Domain A and Domain B and let me map the values such that Code PVC is now code 1

**Comment by SteveGrise** [comment]
Need to do work on domains that do not have matching source/target values - not working correctly. Also need to support subtypes/domains in UI/selections somehow.

**Comment by MikeMillerGIS** [comment]
Linking issues:
https://github.com/Esri/data-assistant/issues/125
https://github.com/Esri/data-assistant/issues/111
https://github.com/Esri/data-assistant/issues/120
https://github.com/Esri/data-assistant/issues/125

**Comment by MikeMillerGIS** [comment]
@SteveGrise 
When trying to resize the domain map window, the internal dialog resized, but the window does not
![image](https://cloud.githubusercontent.com/assets/2707285/24169730/ef76e5cc-0e54-11e7-8aac-b09ed2445f50.png)

**Comment by MikeMillerGIS** [comment]
Linking https://github.com/Esri/data-assistant/issues/136

**Comment by previnWong** [comment]
Closing this was verified by other issues that were resolved.
