### ISSUE TITLE
New public APIs (ArcGIS Pro 2.0)

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/data-assistant#74]
After the release of Pro 1.4, the development team will be deprecating the public APIs and we need to recompile the add-in and certify on Pro 2.0.  

Get @chris-fox @ChrisBuscaglia and others to develop plan and strategy for add-in.

**Comment by ChrisBuscaglia** [comment]
@chris-fox need the recompile for 2.0 @MikeMillerGIS

**Comment by chris-fox** [comment]
@ChrisBuscaglia I recompiled the add-in based on the most recent commit to the Enhancements-WA branch and updated the version in the config for 2.0. There were 2 api changes that needed fixes. I pushed these changes to a new branch call 'build-pro-2.0'. You can download the add-in for 2.0 at the link below.

https://github.com/Esri/data-assistant/raw/build-pro-2.0/ShareGISData/bin/Release/DataAssistant.esriAddinX

**Comment by ChrisBuscaglia** [comment]
@chris-fox perfect, this is good news and thanks for applying the fixes.

@MikeMillerGIS @pLeBlanc93 @previnWong

**Comment by ChrisBuscaglia** [comment]
@chris-fox need a re-compile for ArcGIS Pro 2.0 - have new icons and we applied 2 fixes for 1.4 release that need to be incorporated.

**Comment by chris-fox** [comment]
@ChrisBuscaglia, which branch are the changes in? I am not seeing a commit with new images in the repo. What do you guys think about merging the latest changes into the develop branch so we can just work off that?

@MikeMillerGIS, I was thinking about how to handle this for the deployment tools as well. What do you think about instead of having different branches we have a 2.x and 1.x project in the same branch? I was thinking all the files with no differences can be in a shared directory and only the files that are different for the version would be in version specific subfolders. This way from the same branch we can easily build the 2.x or 1.x version and when we release they both can be pushed to the master branch.

**Comment by ChrisBuscaglia** [comment]
@chris-fox the icons are being worked on by the creative lab.  I'm fine with merging https://github.com/Esri/data-assistant/tree/Enhancements-WA1 into develop.

**Comment by chris-fox** [comment]
@ChrisBuscaglia, now in the develop branch is a 1.4 and a 2.0 solution. In the Shared sub-folder is all the source files and images that remain the same between the versions. In the 1.4 and 2.0 sub-folders are the files that have differences. You can find the compiled add-in for each version under the 1.4 or 2.0 sub folders bin/Release.

**Comment by ChrisBuscaglia** [comment]
@chris-fox thanks
