### ISSUE TITLE
New File fails when there are no maps

### ISSUE THREAD

**Issue by jessnoo** [Esri/data-assistant#75]
If the active project doesn't have any maps, the New File tool fails.  A map should not be required for any of the tools to execute successfully.

![image](https://cloud.githubusercontent.com/assets/6181441/19572173/03c3c502-96b6-11e6-97e8-4421385633f5.png)

**Comment by SteveGrise** [comment]
At Pro 1.3 I do not think it is possible to get the data source path for Enterprise Geodatabase layers the way that I had it working with 1.2 (i.e., Database Connections\test.sde\FClass). As a result, that combined with future automation of DA processes is leading me towards storing the ArcGIS  Pro project location and layer names in the configuration files rather than physical file paths.

The tool should not fail, but the result is that for some layers the only approach that I can get to work is when datasets are layers in the current map.

For now I can prevent the error message except for the Enterprise GDB case.

**Comment by jessnoo** [comment]
Duplicate of #85 ?

**Comment by jessnoo** [comment]
Closing as duplicate of #85
