### ISSUE TITLE
Consider using generic term rather than talking about geometry as Parcels

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#82]
When running an append and presumably when complex geometry is encountered you get an output message: 'Simplifying (densifying) Parcel Geometry'. Maybe we should just say 'Simplifying (densifying geometry'.

**Comment by ChrisBuscaglia** [comment]
@SteveGrise This is probably because we took the original code from community parcels for parcel-specific geometries.  Please see issue #81 - this appears to be failing for some geometries still and I believe that we can move this code to append and more easily debugged if we run into these types of issues in the future.

**Comment by SteveGrise** [comment]
Yes the word Parcel should be dropped.

**Comment by MikeMillerGIS** [comment]
@chris-fox @ChrisBuscaglia can you verify this is resolved?

**Comment by chris-fox** [comment]
Verified
