### ISSUE TITLE
Exception caught: unable to cast DIAMETER to Double  : 'None'

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#99]
Is this a valid exception?  My field map for this has other cast to 0, so I would assume Null in the source would be 0 in the result

@SteveGrise

**Comment by MikeMillerGIS** [comment]
So it appears there is a conversion not preforming correctly.  My source field is a double, the target is int.  The preview dataset is creating a field of double.  This should be int to match the target, is that correct?
@SteveGrise

**Comment by MikeMillerGIS** [comment]
Data for the repo
[ForSteve.zip](https://github.com/Esri/data-assistant/files/733405/ForSteve.zip)

**Comment by SteveGrise** [comment]
Sounds like a bug, if Otherwise is 0 then that should be the value, also
None should be valid unless the field is not nullable.

**Comment by MikeMillerGIS** [comment]
I have a map for every value, I think it is a int to double issue.  The preview database has the source type, not the target type.

**Comment by MikeMillerGIS** [comment]
error occurs line 493 in dlaFieldCalculator.  Val is None and this 
valTest = float(val)

**Comment by MikeMillerGIS** [comment]
Ahh I see the problem, it is looking for DomainMap and not ValueMap, line 391.  Change this will break any existing configs

**Comment by MikeMillerGIS** [comment]
which actually is that you used getValueMap twice

**Comment by SteveGrise** [comment]
@MikeMillerGIS committed a change to fix the typo and None value handling. Looks to me like this will work better for null source and/or target values, let me know if you have any issues. 

Also FYI on fields with the same name and different types between source and target: the field calculator renames the fields, adds a new field with the target type, and then cleans up the fields after running so that there is a field with the right name and type at the completion of the field calculator process... If that is not setup correctly after the calculator is complete then it is a bug.

**Comment by SteveGrise** [comment]
Tested with CurbStopValves.xml. Appears to correctly populate 0/Unknown domain value.

**Comment by MikeMillerGIS** [comment]
verified
